### ISSUE TITLE
Mention minimum Python version

### ISSUE THREAD

**Issue by belzebub40k** [mweinelt/kea-exporter#12]
Since version 0.4.0 kea-exporter no longer runs under Debian 9 with Python 3.5 because it uses f-strings for formatting text. f-strings where introduced in Python 3.6. I don't know if 3.6 is sufficient to run version 0.4.0 as I was only able to test it with 3.5 and 3.7.

https://github.com/mweinelt/kea-exporter/blob/develop/kea_exporter/kea.py#L26

**Comment by mweinelt** [comment]
Yep, it's currently requiring Python 3.6. That is only because of f'strings, if we replaced those it would work in older versions.
