### ISSUE TITLE
Typo in metric name

### ISSUE THREAD

**Issue by francois-maillard** [mweinelt/kea-exporter#13]
There's a typo in the metric referenced there:
https://github.com/mweinelt/kea-exporter/blob/d5d719ca98dcba557aafae2c0d5d117454821126/kea_exporter/kea.py#L338

```python
'metric': 'receoved_packets',
```

**Comment by mweinelt** [comment]
Good catch, thank you. Will do a release shortly, once I remember how to do it :roll_eyes:

**Comment by mweinelt** [comment]
I just released v0.4.1, it's up on Pypi.
