### ISSUE TITLE
Grafana dashboard

### ISSUE THREAD

**Issue by M0NsTeRRR** [mweinelt/kea-exporter#20]
Hello,

Thanks for your exporter it works well !

I haven't seen any dashboard for your exporter so i've created one, if you would like to add it I can create a pull request :)

https://grafana.com/grafana/dashboards/12688

**Comment by mweinelt** [comment]
Awesome, I will add it to the README in the next few days, as I'm a bit short on time right now.

**Comment by M0NsTeRRR** [comment]
Sure, your welcome
