### ISSUE TITLE
TLS/SSL support

### ISSUE THREAD

**Issue by M0NsTeRRR** [mweinelt/kea-exporter#21]
Hello,

Do there any plan to add TLS support like node_exporter to be secured/encrypted ?
https://github.com/prometheus/node_exporter/blob/master/https/README.md

Best regards,

**Comment by mweinelt** [comment]
No, I'm afraid that is out of scope.

I'd recommend reverse proxying the exporter instead. In the simplest case this could be done by https://github.com/QubitProducts/exporter_exporter.

Best regards!

**Comment by M0NsTeRRR** [comment]
Thanks for the link I didn't know, it will be better than running a Nginx server !
