### ISSUE TITLE
Some unhandled metrics

### ISSUE THREAD

**Issue by chayleaf** [mweinelt/kea-exporter#32]
- pool - subnet[id].pool[pid] has a bunch of per-pool stats
- v4-lease-reuses - Number of times an IPv4 lease had its CLTT increased in memory and its expiration time left unchanged in persistent storage as part of the lease caching feature. This is referred to as a lease reuse. This statistic is global.
- v6-ia-na-lease-reuses - Number of times an IA_NA lease had its CLTT increased in memory and its expiration time left unchanged in persistent storage as part of the lease caching feature. This is referred to as a lease reuse. This statistic is global.
- v6-ia-pd-lease-reuses - Number of times an IA_PD lease had its CLTT increased in memory and its expiration time left unchanged in persistent storage as part of the lease caching feature. This is referred to as a lease reuse. This statistic is global.

**Comment by mweinelt** [comment]
Support for per-pool labeling and v4-lease-reuses is now available on `develop`. I will have to upgrade my router to Kea 2.4.0 to test for the other two metrics.
