### ISSUE TITLE
Reasoning for stork alternative

### ISSUE THREAD

**Issue by courtland** [mweinelt/kea-exporter#54]
Hello. Thanks for the work in creating this excellent exporter. I am curious about the reasoning for creating and using this vs. stork / stork-agent? It might be helpful to include some of this knowledge in the README. Thank you.

**Comment by mweinelt** [comment]
Stork simply did not exist way back when I started this project. See https://gitlab.isc.org/isc-projects/kea/-/issues/279.

**Comment by M0NsTeRRR** [comment]
Also, some users don't need every feature that Stork offers; they only require a simple Prometheus exporter. That's why I won't switch to Stork.

**Comment by courtland** [comment]
Thanks for your valued input!
