### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by mathiasAichinger** [mweinelt/kea-exporter#8]
Hi,
I'm having various problems getting the kea-exporter running. Which Python version are you using?

**Comment by mathiasAichinger** [comment]
With my default python 2.7 I had problems with the bytes method and I got `str() takes at most 1 argument (2 given)` 

With python 3.5 I always got the following error:

```
➜  ~ kea-exporter /usr/local/etc/kea/kea-dhcp4.conf
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.5.0/bin/kea-exporter", line 11, in <module>
    sys.exit(cli())
TypeError: 'module' object is not callable
```

I solved it by changing the import in /home/user/.pyenv/versions/3.5.0/bin/kea-exporter from
`from kea_exporter import cli` to `from kea_exporter.cli import cli`

**Comment by mweinelt** [comment]
Version bumped and uploaded to pypi. I hope that solves the issue mentioned.

**Comment by mathiasAichinger** [comment]
Fixed. thx 👍
